<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from /home/seamus/buildkit/build/47-test/web/sites/default/files/civicrm/ext/biz.jmaconsulting.pricefieldcondition/xml/schema/CRM/Pricefieldcondition/PriceFieldCondition.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:6764610259eb5a84b35f9e7d77502d53)
 */

/**
 * Database access object for the PriceFieldCondition entity.
 */
class CRM_Pricefieldcondition_DAO_PriceFieldCondition extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_price_field_condition';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique PriceFieldCondition ID
   *
   * @var int
   */
  public $id;

  /**
   * Entity id of the entity we are affecting
   *
   * @var int
   */
  public $entity_id;

  /**
   * Entity table of the affacted entity
   *
   * @var string
   */
  public $entity_table;

  /**
   * Entity id that determines if this entity is visible or not
   *
   * @var int
   */
  public $condition_entity_id;

  /**
   * Entity table of the condition
   *
   * @var string
   */
  public $condition_entity_table;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_price_field_condition';
    parent::__construct();
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Pricefieldcondition_ExtensionUtil::ts('Unique PriceFieldCondition ID'),
          'required' => TRUE,
          'where' => 'civicrm_price_field_condition.id',
          'table_name' => 'civicrm_price_field_condition',
          'entity' => 'PriceFieldCondition',
          'bao' => 'CRM_Pricefieldcondition_DAO_PriceFieldCondition',
          'localizable' => 0,
        ],
        'entity_id' => [
          'name' => 'entity_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Pricefieldcondition_ExtensionUtil::ts('Entity id of the entity we are affecting'),
          'where' => 'civicrm_price_field_condition.entity_id',
          'table_name' => 'civicrm_price_field_condition',
          'entity' => 'PriceFieldCondition',
          'bao' => 'CRM_Pricefieldcondition_DAO_PriceFieldCondition',
          'localizable' => 0,
        ],
        'entity_table' => [
          'name' => 'entity_table',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Pricefieldcondition_ExtensionUtil::ts('Entity Table'),
          'description' => CRM_Pricefieldcondition_ExtensionUtil::ts('Entity table of the affacted entity'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_price_field_condition.entity_table',
          'table_name' => 'civicrm_price_field_condition',
          'entity' => 'PriceFieldCondition',
          'bao' => 'CRM_Pricefieldcondition_DAO_PriceFieldCondition',
          'localizable' => 0,
        ],
        'condition_entity_id' => [
          'name' => 'condition_entity_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Pricefieldcondition_ExtensionUtil::ts('Entity id that determines if this entity is visible or not'),
          'where' => 'civicrm_price_field_condition.condition_entity_id',
          'table_name' => 'civicrm_price_field_condition',
          'entity' => 'PriceFieldCondition',
          'bao' => 'CRM_Pricefieldcondition_DAO_PriceFieldCondition',
          'localizable' => 0,
        ],
        'condition_entity_table' => [
          'name' => 'condition_entity_table',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Pricefieldcondition_ExtensionUtil::ts('Condition Entity Table'),
          'description' => CRM_Pricefieldcondition_ExtensionUtil::ts('Entity table of the condition'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_price_field_condition.condition_entity_table',
          'table_name' => 'civicrm_price_field_condition',
          'entity' => 'PriceFieldCondition',
          'bao' => 'CRM_Pricefieldcondition_DAO_PriceFieldCondition',
          'localizable' => 0,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'price_field_condition', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'price_field_condition', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'UI_entity_id_entity_table_condition' => [
        'name' => 'UI_entity_id_entity_table_condition',
        'field' => [
          0 => 'entity_id',
          1 => 'entity_table',
          2 => 'condition_entity_id',
          3 => 'condition_entity_table',
        ],
        'localizable' => FALSE,
        'unique' => TRUE,
        'sig' => 'civicrm_price_field_condition::1::entity_id::entity_table::condition_entity_id::condition_entity_table',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
