-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--


-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the exisiting tables
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_price_field_condition`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_price_field_condition
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_price_field_condition` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique PriceFieldCondition ID',
     `entity_id` int unsigned    COMMENT 'Entity id of the entity we are affecting',
     `entity_table` varchar(255)    COMMENT 'Entity table of the affacted entity',
     `condition_entity_id` int unsigned    COMMENT 'Entity id that determines if this entity is visible or not',
     `condition_entity_table` varchar(255)    COMMENT 'Entity table of the condition' 
,
        PRIMARY KEY (`id`)
 
    ,     UNIQUE INDEX `UI_entity_id_entity_table_condition`(
        entity_id
      , entity_table
      , condition_entity_id
      , condition_entity_table
  )
  
 
)    ;

 
